variavel = input("Digite algo: ")
print("O tipo da variável é {}".format(type(variavel)))
print("Só tem espaços? {}".format(variavel.isspace()))
print("É um numérico? {}".format(variavel.isnumeric()))
print("É alfabético? {}".format(variavel.isalpha()))
print("É alfanumérico? {}".format(variavel.isalnum()))
print("Está em maiúsculas? {}".format(variavel.isupper()))
print("Está em minusculas? {}".format(variavel.islower()))
print("Está capitalizada? {}".format(variavel.istitle()))